FROM osrf/ros:humble-desktop

RUN apt update && apt install -y \
    git \
    vim \
    wget \
    ros-humble-dynamixel-sdk \
    ros-humble-turtlebot3-msgs \
    ros-humble-turtlebot3

# Compile and install MQTT
RUN git clone https://github.com/eclipse/paho.mqtt.c.git && \
    cd paho.mqtt.c && \
    cmake \
        -DPAHO_BUILD_STATIC=TRUE \
        -DPAHO_HIGH_PERFORMANCE=TRUE \
        -DPAHO_WITH_SSL=TRUE && \
    cmake --build . --target install && \
    cd .. && rm -rf paho.mqtt.c && \
    git clone https://github.com/eclipse/paho.mqtt.cpp.git && \
    cd paho.mqtt.cpp && \
    cmake \
        -Bbuild \
        -H. \
        -DPAHO_BUILD_STATIC=ON \
        -DPAHO_BUILD_DOCUMENTATION=OFF && \
    cd build && cmake --build . --target install && \
    cd ../.. && rm -rf paho.mqtt.cpp

RUN apt install -y python3-pip && \
    pip3 install paho-mqtt

RUN echo source /opt/ros/humble/setup.bash >> ~/.bashrc
